### ISSUE TITLE
why vertical

### ISSUE THREAD

**Issue by wanghaisheng** [felix-berlin/astro-breadcrumbs#128]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

astro latest
![image](https://github.com/felix-berlin/astro-breadcrumbs/assets/2363295/bb8e4174-60c3-49b9-b7ac-70419eb4f289)
![image](https://github.com/felix-berlin/astro-breadcrumbs/assets/2363295/bcc31d1e-95cc-45c0-82f2-16b13580ef6e)

**Comment by felix-berlin** [comment]
Hey, the component does not import the associated styles automatically. You can choose between CSS and SCSS API.

Docs --> https://docs.astro-breadcrumbs.kasimir.dev/en/setup-scss-config/

**Comment by felix-berlin** [comment]
If you want a quick result use the CSS file:

```js
---
import 'astro-breadcrumbs/breadcrumbs.css';
---
```

**Comment by wanghaisheng** [comment]
thanks
