### ISSUE TITLE
Make it possible to not show the last (current) crumb

### ISSUE THREAD

**Issue by JanMisker** [felix-berlin/astro-breadcrumbs#228]
Thanks for this package!

The breadcrumbs now always show the current page as well, but in our case we usually display that page title as a header right below the breadcrumbs. So it looks a bit redundant.

It would be nice if there is a property to not display the last/current crumb.

**Comment by felix-berlin** [comment]
Hi @JanMisker, good idea. Will put this improvement in the next release 🙂

**Comment by JanMisker** [comment]
It seems that also the parent of the current page is omitted, could that be? I'm a new Astro builder, if you can point me to where I can create an example I'd be happy to provide it.

**Comment by felix-berlin** [comment]
@JanMisker It may well be that a bug has crept in there. I'll check it out and create a fix.
