### ISSUE TITLE
Slash in base breaks breadcrumbs

### ISSUE THREAD

**Issue by joppekroon** [felix-berlin/astro-breadcrumbs#262]
**Describe the bug**
I need to set a base in `astro.config.mjs` that contains a slash, like `foo/bar`.
This unfortunately is not handled correctly, as it generates both a "Home" and homepage-name link on the home page (same for deeper pages). The "Home" link also goes back one level too deep, i.e. it links to `/foo`.

**To Reproduce**
Set the base property in `astro.config.mjs` to `foo/bar`.

**Expected behavior**
The "Home" crumb links to `foo/bar` and there is not an additional link for the home page.

**Comment by felix-berlin** [comment]
Thank you for the detailed issue. I also noticed your pull request, thanks for your efforts.

I think I'll find time for it at the weekend.

**Comment by felix-berlin** [comment]
Should be fixed by your PR ❤️ https://github.com/felix-berlin/astro-breadcrumbs/pull/264

**Comment by joppekroon** [comment]
Thanks for picking it up!
