### ISSUE TITLE
Disable a breadcrumb

### ISSUE THREAD

**Issue by jvlvl-z** [felix-berlin/astro-breadcrumbs#329]
Hi,

It would be great if we could just disable the first link (or any breadcrumb by passing the index to the setting). When you're browsing a catalogue it's not really necessary to always see "home" there. 

Thanks!

**Comment by felix-berlin** [comment]
To achieve this, you are welcome to read the new guide [Disable or remove crumb(s)](https://docs.astro-breadcrumbs.kasimir.dev/guides/disable-or-remove-crumb/).
