### ISSUE TITLE
Custom attributes on breadcrumb items

### ISSUE THREAD

**Issue by thomascoppein** [felix-berlin/astro-breadcrumbs#370]
**Is your feature request related to a problem? Please describe.**
When using Astro's Page Transitions it's neccesary to add the `data-astro-history="push"` to links.

**Describe the solution you'd like**
I would like te add custom attributes on the breadcrumb items.

**Comment by felix-berlin** [comment]
Hi @thomascoppein ,
you can achieve this using the customizeListElements prop. See: https://docs.astro-breadcrumbs.kasimir.dev/configuration/properties/#customizelistelements

**Comment by thomascoppein** [comment]
Thanks, It works!
