### ISSUE TITLE
Thanx and - how to install?

### ISSUE THREAD

**Issue by impactfactory** [felix-berlin/astro-breadcrumbs#4]
After the CLI-Installation and the copy and pasting as described, no output is occuring. Does it need two additional lines in astro.config.mjs like this?

```
import breadcrumbs from "@astrojs/breadcrumbs"; 
...
 breadcrumbs()
```
Is it possible to put the Component into the Layout or does it have to be in the page? Can it handle paths generated with getStaticPaths() too?

Thanks a lot for the work!!

**Comment by felix-berlin** [comment]
Hey, sorry for the late response.

Here is an example of how to include the Breadcrumps component.

```astro.js
---
import { Breadcrumbs } from "astro-breadcrumbs";
---

<Breadcrumbs indexText={"Start"}>
```

You don't need to change anything in the astro.config.mjs config file.

So far the component does not work with `getStaticPaths()`, for creating the paths I currently use `Astro.url.pathname`.
But I like to look at how this could work well with `getStaticPaths()` :)

In the future I will provide a way to configure the paths with a property. So a kind of manual mode.

Both, pages and layout should work.

**Comment by felix-berlin** [comment]
The CodeSandBox example shows quite well how it can be used --> [Example](https://codesandbox.io/p/sandbox/astro-breadcrumbs-kl3oj6?file=%2Fsrc%2Fpages%2Fen%2Fcategory%2Fexample%2Fmy-page.astro&selection=%5B%7B%22endColumn%22%3A8%2C%22endLineNumber%22%3A12%2C%22startColumn%22%3A8%2C%22startLineNumber%22%3A12%7D%5D)

**Comment by impactfactory** [comment]
Thanx a lot!
